name: Continuous Delivery to Development

on:
  workflow_call:

env:
  SERVER_IP: "10.10.10.30"

permissions:
  contents: read

jobs:
  Deploy-App:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Declare variables
        id: vars
        shell: bash
        run: echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"
      - name: Displaying ...
        run: echo "${{ steps.vars.output.commit_sha}}"
      # - name: Creating Docker image and deploy ...
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DEV_HOST }}
      #     username: ${{ secrets.DEV_USERNAME }}
      #     key: ${{ secrets.DEV_KEY }}
      #     script: |
      #       sudo docker build --force-rm -f ./Dockerfile -t outline-digital:dev-${{ steps.vars.output.commit_sha}}
