name: Continuous Delivery to Production

on:
  workflow_call:

env:
  HOST: ${{ secrets.PRD_HOST }}
  USERNAME: ${{ secrets.PRD_USERNAME }}
  KEY: ${{ secrets.PRD_KEY }}

permissions:
  contents: read

jobs:
  Deploy-App:
    name: Deploy APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Declare variables
        id: vars
        shell: bash
        run: echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"
      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: $HOST
          username: $USERNAME
          key: $KEY
          source: "./*"
          target: "/home/$USERNAME/outline-digital"
      - name: Creating Docker image ...
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $USERNAME
          key: $KEY
          script: |
            sudo docker build -f ./Dockerfile.prod -t outline-digital:prd-${{ steps.vars.output.commit_sha}}
      - name: Deploying Docker container ...
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $USERNAME
          key: $KEY
          script: |
            cd ~/outline-digital; sed -i -e "s|image:.*outline-digital*|image: outline-digital:prd-${{ steps.vars.output.commit_sha}}|" docker-compose.yaml
            sudo docker-compose -f docker-compose.yaml up -d outline-digital
            sed -i -e "s|image:.*outline-digital:prd-.*|image: outline-digital|" docker-compose.yaml'
