name: NodeJS Application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Code-Quality-Checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pre-commit
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pre-commit
      - name: Checking files
        run: |
          git clean -dfx
          pre-commit run --all-files
  Dockerfile-Quality-Checks:
    name: Dockerfile Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./Dockerfile
