name: NodeJS Application

on: push

permissions:
  contents: read

jobs:
  Code-Quality-Checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pre-commit
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pre-commit
      - name: Checking files
        run: |
          git clean -dfx
          pre-commit run --all-files
  Dockerfile-Quality-Checks:
    name: Dockerfile Quality Checks
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
          no-fail: true
          # output-file: dockerlint-results.sarif
      #     no-fail: true
      # - name: Save results as a artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dockerlint-results.sarif
      #     path: ./dockerlint-results.sarif
  Deploy-Application:
    needs: ["Code-Quality-Checks", "Dockerfile-Quality-Checks"]
    name: Deploying application
    uses: ./.github/workflows/deployment.yml
